version: '3'
services:
  hyperf:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "9511:9501"
      - "9512:9502"
    depends_on:
      - mysql
      - redis
      - elasticsearch
    environment:
      - APP_ENV=local
    user: root
    privileged: true
    stdin_open: true
    restart: always
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0-debian
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hyperf
      - MYSQL_USER=hyperf
      - MYSQL_PASSWORD=hyperf
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    ports:
      - "3366:3306"
    networks:
      - mynetwork
  mysql_exporter:
    image: prom/mysqld-exporter
    environment:
      DATA_SOURCE_NAME: root:root@tcp(mysql:3306)/hyperf
    command:
      - '--collect.global_status'
      - '--collect.info_schema.query_response_time'
      - '--collect.info_schema.tablestats'
      - '--collect.info_schema.tables'
      - '--collect.info_schema.userstats'
      - '--collect.perf_schema.eventsstatements'
      - '--collect.perf_schema.eventswaits'
      - '--collect.perf_schema.file_events'
      - '--collect.slave_status'
    ports:
      - 9104:9104
    networks:
      - mynetwork      
        
  redis:
    image: redis:5.0
    ports:
      - "6399:6379"
    networks:
      - mynetwork

  redis_exporter:
    image: oliver006/redis_exporter
    ports:
      - 9121:9121
    networks:
      - mynetwork      
  
  elasticsearch:
    build:
      context: ./
      dockerfile: Dockerfile.elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana:9.5.2
    ports:
      - "3000:3000"
    depends_on:
      - loki
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - mynetwork

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-storage:/loki
    networks:
      - mynetwork

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./runtime/logs:/var/logs
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - mynetwork
  node_exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    ports:
      - "9100:9100"
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - node_exporter
    networks:
      - mynetwork      

volumes:
  mysql_data:
  redis_data:
  esdata:
  grafana-storage:
  loki-storage:

networks:
  mynetwork:
