version: '3'
services:
  hyperf:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "9511:9501"
      - "9512:9502"
    depends_on:
      - mysql
      - redis
      - elasticsearch
    environment:
      - APP_ENV=local
    user: root
    privileged: true
    stdin_open: true
    restart: always
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0-debian
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hyperf
      - MYSQL_USER=hyperf
      - MYSQL_PASSWORD=hyperf
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    ports:
      - "3366:3306"
    networks:
      - mynetwork
        
  redis:
    image: redis:5.0
    ports:
      - "6399:6379"
    networks:
      - mynetwork
  
  elasticsearch:
    build:
      context: ./
      dockerfile: Dockerfile.elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - "ELASTIC_USERNAME=username"    
      - "ELASTIC_PASSWORD=a123456"
      - "discovery.type=single-node"
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana:9.5.2
    ports:
      - "3000:3000"
    depends_on:
      - loki
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - mynetwork

  loki:
    image: grafana/loki:2.4.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-storage:/loki
    networks:
      - mynetwork

  promtail:
    image: grafana/promtail:2.4.1
    volumes:
      - ./runtime/logs:/var/logs
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - mynetwork

volumes:
  mysql_data:
  redis_data:
  esdata:
  grafana-storage:
  loki-storage:

networks:
  mynetwork:
