global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'hyperf'
    scrape_interval: 5s
    static_configs:
      - targets: ['hyperf:9502']      

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql_exporter:9104']
  
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
